shellcheck fixes

diff --git a/extras/cronwrapper b/extras/cronwrapper
--- a/extras/cronwrapper
+++ b/extras/cronwrapper
@@ -35,29 +35,29 @@ elif [ ${EUID} -eq 0 ]; then
   fi
 fi
 
-if [ ! -z "$CONF" ]; then
-  # We have a config file, prefix it with parameter
-  if [ ! -f "${CONF}" ]; then
-    echo "ERROR: Cannot find config file (tried ${CONF})" >&2
-    exit 255
-  fi
-  CONF="--config=${CONF}"
+if [ -n "$CONF" ]; then
+	# We have a config file, prefix it with parameter
+	if [ ! -f "${CONF}" ]; then
+		echo "ERROR: Cannot find config file (tried ${CONF})" >&2
+		exit 255
+	fi
+	CONF="--config=${CONF}"
 fi
 
 LOGFILE=$(mktemp /tmp/plexupdate.cron.XXXX)
 
 RET=0
 if $LOGGING; then
-  "${SCRIPT}" "${CONF}" 2>&1 | tee ${LOGFILE} | logger -t plexupdate -p daemon.info
-  RET="${PIPESTATUS[0]}"
+  "${SCRIPT}" "${CONF}" 2>&1 | tee "${LOGFILE}" | logger -t plexupdate -p daemon.info
+	RET="${PIPESTATUS[0]}"
 else
-  "${SCRIPT}" "${CONF}" >${LOGFILE} 2>&1
-  RET=$?
+  "${SCRIPT}" "${CONF}" >"${LOGFILE}" 2>&1
+	RET=$?
 fi
 
 if [ $RET -ne 0 ]; then
-  # Make sure user gets an email about this (when not success or if user has specified when)
-  cat ${LOGFILE} >&2
+	# Make sure user gets an email about this (when not success or if user has specified when)
+  cat "${LOGFILE}" >&2
 
   # Output will produce a cron email, so we can reset the exit status
   if [ $RET -eq 10 ]; then
