refactor to get the version in cronwrapper

diff --git a/extras/cronwrapper b/extras/cronwrapper
--- a/extras/cronwrapper
+++ b/extras/cronwrapper
@@ -38,15 +38,47 @@ elif [ ${EUID} -eq 0 ]; then
   fi
 fi
 
+SCRIPT_PATH="$(dirname "${SCRIPT}")"
+SCRIPT_CORE="${SCRIPT_PATH}/plexupdate-core"
+
+if ! source "${SCRIPT_CORE}"; then
+  echo "ERROR: plexupdate-core can't be found. Please redownload plexupdate and try again." >&2
+  exit 255
+fi
+
 if [ -n "$CONF" ]; then
   # We have a config file, prefix it with parameter
   if [ ! -f "${CONF}" ]; then
     echo "ERROR: Cannot find config file (tried ${CONF})" >&2
     exit 255
   fi
+
+  source "${CONF}"
+  # DKTODO: only for testing
+  echo ' --> hier3'
+  echo "${CONF}"
+  echo $VERBOSE
+  echo ' <-- hier3'
   CONF="--config=${CONF}"
 fi
 
+# get the current version
+PLEX_CURRENT_VERSION="$(getPlexVersion)"
+
+# get thew new version
+getPlexTokenForDownload
+retrieveDownloadList
+getDistro
+parseDownloadList
+extractFilenameFromDownload
+PLEX_NEW_VERSION="$(parseVersion "${FILENAME}")"
+# DKTODO: only for testing
+echo ' --> hier2'
+echo $VERBOSE
+echo $TOKEN
+echo ${DOWNLOAD}
+echo ${FILENAME}
+echo ' <-- hier2'
 LOGFILE=$(mktemp /tmp/plexupdate.cron.XXXX)
 
 RET=0
@@ -58,6 +90,12 @@ else
   RET=$?
 fi
 
+# DKTODO: only for testing
+echo ' --> hier'
+echo "$PLEX_CURRENT_VERSION"
+echo "$PLEX_NEW_VERSION"
+echo ' <-- hier'
+
 if [ $RET -ne 0 ]; then
   # DKTODO: maybe move cron notification into the notify script?
   # Make sure user gets an email about this (when not success or if user has specified when)
@@ -65,7 +103,7 @@ if [ $RET -ne 0 ]; then
 
   # execute notify-script if defined and available
   if [ -n "${CRON_NOTIFY_SCRIPT}" ] && [ -f "${CRON_NOTIFY_SCRIPT}" ]; then
-    source "${CRON_NOTIFY_SCRIPT}" "${LOGFILE}" "${RET}"
+    source "${CRON_NOTIFY_SCRIPT}"
   fi
 
   # Output will produce a cron email, so we can reset the exit status
diff --git a/plexupdate-core b/plexupdate-core
--- a/plexupdate-core
+++ b/plexupdate-core
@@ -73,7 +73,7 @@ getPlexServerToken() {
   for I in "${VALIDPATHS[@]}"; do
     if [ ! -z "${I}" -a -f "${I}${PREFFILE}" ]; then
       # When running installer.sh directly from wget, $0 will return bash
-      if [ "$(basename $0)" = "installer.sh" -o "$(basename $0)" = "bash" ]; then
+      if [ "$(basename "${BASH_SOURCE[0]}")" = "installer.sh" -o "$(basename "${BASH_SOURCE[0]}")" = "bash" ]; then
         TOKEN=$(sudo sed -n 's/.*PlexOnlineToken="\([[:alnum:]_-]*\).*".*/\1/p' "${I}${PREFFILE}" 2>/dev/null)
       else
         TOKEN=$(sed -n 's/.*PlexOnlineToken="\([[:alnum:]_-]*\).*".*/\1/p' "${I}${PREFFILE}" 2>/dev/null)
@@ -243,6 +243,69 @@ getPlexVersion() {
     error "Unknown OS, exiting."
     exit 1
   fi
+}
+
+getPlexTokenForDownload() {
+  if [ "${PUBLIC}" = "no" ] && ! getPlexToken; then
+    error "Unable to get Plex token, falling back to public release"
+    PUBLIC="yes"
+  fi
+
+  if [ "$PUBLIC" != "no" ]; then
+    # It's a public version, so change URL
+    URL_DOWNLOAD=${URL_DOWNLOAD_PUBLIC}
+  fi
+}
+
+retrieveDownloadList() {
+  # Set "X-Plex-Token" to the auth token, if no token is specified or it is invalid, the list will return public downloads by default
+  wgetresults="$(wget --header "X-Plex-Token:\"${TOKEN}\"" "${URL_DOWNLOAD}" -o "${FILE_WGETLOG:-/dev/null}" -O -)"
+
+  if [ $? -ne 0 ]; then
+    error "Unable to retrieve the URL needed for download due to a wget error, run with -v for details"
+    [ "$VERBOSE" = "yes" ] && cat "${FILE_WGETLOG}"
+    exit 1
+  fi
+}
+
+parseDownloadList() {
+  RELEASE=$(grep -ioe '"label"[^}]*' <<<"${wgetresults}" | grep -i "\"distro\":\"${DISTRO}\"" | grep -m1 -i "\"build\":\"${BUILD}\"")
+  DOWNLOAD=$(echo "${RELEASE}" | grep -m1 -ioe 'https://[^\"]*')
+  CHECKSUM=$(echo "${RELEASE}" | grep -ioe '\"checksum\"\:\"[^\"]*' | sed 's/\"checksum\"\:\"//')
+}
+
+extractFilenameFromDownload() {
+  FILENAME="$(basename 2>/dev/null "${DOWNLOAD}")"
+  if [ $? -ne 0 ]; then
+    error "Failed to parse HTML, download cancelled."
+    exit 3
+  fi
+}
+
+getDistro() {
+  if [ -z "${DISTRO_INSTALL}" ]; then
+	if [ -z "${DISTRO}" ]; then
+		# Detect if we're running on redhat instead of ubuntu
+		if [ -f /etc/redhat-release ]; then
+			REDHAT=yes
+			DISTRO="redhat"
+			if ! hash dnf 2>/dev/null; then
+				DISTRO_INSTALL="${REDHAT_INSTALL/dnf/yum}"
+			else
+				DISTRO_INSTALL="${REDHAT_INSTALL}"
+			fi
+		else
+			REDHAT=no
+			DISTRO="debian"
+			DISTRO_INSTALL="${DEBIAN_INSTALL}"
+		fi
+	fi
+else
+	if [ -z "${DISTRO}" -o -z "${BUILD}" ]; then
+		error "Using custom DISTRO_INSTALL requires custom DISTRO and BUILD too"
+		exit 255
+	fi
+fi
 }
 
 verboseOutput() {
